# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Mar 23 10:49:01 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setEnabled(True)
        self.tabMain.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabFix = QtGui.QWidget()
        self.tabFix.setObjectName(_fromUtf8("tabFix"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabFix)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lstFLists = QtGui.QListWidget(self.tabFix)
        self.lstFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lstFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lstFLists.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lstFLists.setObjectName(_fromUtf8("lstFLists"))
        self.gridLayout_2.addWidget(self.lstFLists, 1, 1, 1, 1)
        self.lblFLists = QtGui.QLabel(self.tabFix)
        self.lblFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lblFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFLists.setFont(font)
        self.lblFLists.setObjectName(_fromUtf8("lblFLists"))
        self.gridLayout_2.addWidget(self.lblFLists, 0, 1, 1, 1)
        self.btnFStart = QtGui.QPushButton(self.tabFix)
        self.btnFStart.setEnabled(False)
        self.btnFStart.setMinimumSize(QtCore.QSize(175, 0))
        self.btnFStart.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btnFStart.setObjectName(_fromUtf8("btnFStart"))
        self.gridLayout_2.addWidget(self.btnFStart, 2, 1, 1, 1)
        self.lblFFileList = QtGui.QLabel(self.tabFix)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFFileList.setFont(font)
        self.lblFFileList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblFFileList.setObjectName(_fromUtf8("lblFFileList"))
        self.gridLayout_2.addWidget(self.lblFFileList, 0, 0, 1, 1)
        self.tblFFileList = QtGui.QTableWidget(self.tabFix)
        self.tblFFileList.setAcceptDrops(True)
        self.tblFFileList.setDragEnabled(False)
        self.tblFFileList.setAlternatingRowColors(True)
        self.tblFFileList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblFFileList.setObjectName(_fromUtf8("tblFFileList"))
        self.tblFFileList.setColumnCount(0)
        self.tblFFileList.setRowCount(0)
        self.tblFFileList.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tblFFileList, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnFAddFiles = QtGui.QPushButton(self.tabFix)
        self.btnFAddFiles.setObjectName(_fromUtf8("btnFAddFiles"))
        self.horizontalLayout_6.addWidget(self.btnFAddFiles)
        self.btnFAddFolder = QtGui.QPushButton(self.tabFix)
        self.btnFAddFolder.setObjectName(_fromUtf8("btnFAddFolder"))
        self.horizontalLayout_6.addWidget(self.btnFAddFolder)
        self.btnFRemoveFiles = QtGui.QPushButton(self.tabFix)
        self.btnFRemoveFiles.setEnabled(False)
        self.btnFRemoveFiles.setObjectName(_fromUtf8("btnFRemoveFiles"))
        self.horizontalLayout_6.addWidget(self.btnFRemoveFiles)
        self.btnFClearList = QtGui.QPushButton(self.tabFix)
        self.btnFClearList.setEnabled(False)
        self.btnFClearList.setObjectName(_fromUtf8("btnFClearList"))
        self.horizontalLayout_6.addWidget(self.btnFClearList)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.tabMain.addTab(self.tabFix, _fromUtf8(""))
        self.tabLists = QtGui.QWidget()
        self.tabLists.setObjectName(_fromUtf8("tabLists"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabLists)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tblLLists = QtGui.QTableWidget(self.tabLists)
        self.tblLLists.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblLLists.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblLLists.setObjectName(_fromUtf8("tblLLists"))
        self.tblLLists.setColumnCount(0)
        self.tblLLists.setRowCount(0)
        self.tblLLists.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tblLLists)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnLInsertRow = QtGui.QPushButton(self.tabLists)
        self.btnLInsertRow.setEnabled(False)
        self.btnLInsertRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLInsertRow.setObjectName(_fromUtf8("btnLInsertRow"))
        self.verticalLayout.addWidget(self.btnLInsertRow)
        self.btnLDeleteRow = QtGui.QPushButton(self.tabLists)
        self.btnLDeleteRow.setEnabled(False)
        self.btnLDeleteRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLDeleteRow.setObjectName(_fromUtf8("btnLDeleteRow"))
        self.verticalLayout.addWidget(self.btnLDeleteRow)
        self.btnLUpdateRow = QtGui.QPushButton(self.tabLists)
        self.btnLUpdateRow.setEnabled(False)
        self.btnLUpdateRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLUpdateRow.setObjectName(_fromUtf8("btnLUpdateRow"))
        self.verticalLayout.addWidget(self.btnLUpdateRow)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabMain.addTab(self.tabLists, _fromUtf8(""))
        self.tabCorrections = QtGui.QWidget()
        self.tabCorrections.setObjectName(_fromUtf8("tabCorrections"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabCorrections)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tblCCorrections = QtGui.QTableWidget(self.tabCorrections)
        self.tblCCorrections.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblCCorrections.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblCCorrections.setObjectName(_fromUtf8("tblCCorrections"))
        self.tblCCorrections.setColumnCount(0)
        self.tblCCorrections.setRowCount(0)
        self.tblCCorrections.horizontalHeader().setVisible(False)
        self.tblCCorrections.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tblCCorrections)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblCorrectionsSelectMode = QtGui.QLabel(self.tabCorrections)
        self.lblCorrectionsSelectMode.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCorrectionsSelectMode.setFont(font)
        self.lblCorrectionsSelectMode.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblCorrectionsSelectMode.setObjectName(_fromUtf8("lblCorrectionsSelectMode"))
        self.verticalLayout_2.addWidget(self.lblCorrectionsSelectMode)
        self.cboCCorrectionMode = QtGui.QComboBox(self.tabCorrections)
        self.cboCCorrectionMode.setMinimumSize(QtCore.QSize(150, 0))
        self.cboCCorrectionMode.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboCCorrectionMode.setObjectName(_fromUtf8("cboCCorrectionMode"))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cboCCorrectionMode)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.lblCList = QtGui.QLabel(self.tabCorrections)
        self.lblCList.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCList.setFont(font)
        self.lblCList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblCList.setObjectName(_fromUtf8("lblCList"))
        self.verticalLayout_2.addWidget(self.lblCList)
        self.cboCList = QtGui.QComboBox(self.tabCorrections)
        self.cboCList.setMinimumSize(QtCore.QSize(150, 0))
        self.cboCList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboCList.setEditable(False)
        self.cboCList.setObjectName(_fromUtf8("cboCList"))
        self.verticalLayout_2.addWidget(self.cboCList)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.btnCInsertRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCInsertRow.setEnabled(False)
        self.btnCInsertRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCInsertRow.setObjectName(_fromUtf8("btnCInsertRow"))
        self.verticalLayout_2.addWidget(self.btnCInsertRow)
        self.btnCDeleteRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCDeleteRow.setEnabled(False)
        self.btnCDeleteRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCDeleteRow.setObjectName(_fromUtf8("btnCDeleteRow"))
        self.verticalLayout_2.addWidget(self.btnCDeleteRow)
        self.btnCUpdateRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCUpdateRow.setEnabled(False)
        self.btnCUpdateRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCUpdateRow.setObjectName(_fromUtf8("btnCUpdateRow"))
        self.verticalLayout_2.addWidget(self.btnCUpdateRow)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabMain.addTab(self.tabCorrections, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.lblSFileEncoding = QtGui.QLabel(self.tabSettings)
        self.lblSFileEncoding.setGeometry(QtCore.QRect(10, 10, 175, 16))
        self.lblSFileEncoding.setMinimumSize(QtCore.QSize(175, 0))
        self.lblSFileEncoding.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSFileEncoding.setFont(font)
        self.lblSFileEncoding.setObjectName(_fromUtf8("lblSFileEncoding"))
        self.cboSFileEncoding = QtGui.QComboBox(self.tabSettings)
        self.cboSFileEncoding.setGeometry(QtCore.QRect(10, 30, 175, 22))
        self.cboSFileEncoding.setMinimumSize(QtCore.QSize(175, 0))
        self.cboSFileEncoding.setMaximumSize(QtCore.QSize(175, 16777215))
        self.cboSFileEncoding.setObjectName(_fromUtf8("cboSFileEncoding"))
        self.chkSRemoveEmpty = QtGui.QCheckBox(self.tabSettings)
        self.chkSRemoveEmpty.setGeometry(QtCore.QRect(10, 70, 381, 16))
        self.chkSRemoveEmpty.setChecked(True)
        self.chkSRemoveEmpty.setObjectName(_fromUtf8("chkSRemoveEmpty"))
        self.tabMain.addTab(self.tabSettings, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_file = QtGui.QAction(MainWindow)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionWiki = QtGui.QAction(MainWindow)
        self.actionWiki.setObjectName(_fromUtf8("actionWiki"))
        self.actionOpen_files = QtGui.QAction(MainWindow)
        self.actionOpen_files.setObjectName(_fromUtf8("actionOpen_files"))
        self.actionAdd_new_dictionary_type = QtGui.QAction(MainWindow)
        self.actionAdd_new_dictionary_type.setObjectName(_fromUtf8("actionAdd_new_dictionary_type"))
        self.actionAdd_new_correction_type = QtGui.QAction(MainWindow)
        self.actionAdd_new_correction_type.setObjectName(_fromUtf8("actionAdd_new_correction_type"))
        self.actionOpenDatabase = QtGui.QAction(MainWindow)
        self.actionOpenDatabase.setObjectName(_fromUtf8("actionOpenDatabase"))
        self.actionCreateDatabase = QtGui.QAction(MainWindow)
        self.actionCreateDatabase.setObjectName(_fromUtf8("actionCreateDatabase"))
        self.actionAddNewCorrectionType = QtGui.QAction(MainWindow)
        self.actionAddNewCorrectionType.setObjectName(_fromUtf8("actionAddNewCorrectionType"))
        self.menuFile.addAction(self.actionCreateDatabase)
        self.menuFile.addAction(self.actionOpenDatabase)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionWiki)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "bwReplacer", None))
        self.lblFLists.setText(_translate("MainWindow", "Lists", None))
        self.btnFStart.setText(_translate("MainWindow", "Start", None))
        self.lblFFileList.setText(_translate("MainWindow", "File list", None))
        self.btnFAddFiles.setText(_translate("MainWindow", "Add files", None))
        self.btnFAddFolder.setText(_translate("MainWindow", "Add folder", None))
        self.btnFRemoveFiles.setText(_translate("MainWindow", "Remove files", None))
        self.btnFClearList.setText(_translate("MainWindow", "Clear list", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabFix), _translate("MainWindow", "Fix", None))
        self.btnLInsertRow.setText(_translate("MainWindow", "Insert row", None))
        self.btnLDeleteRow.setText(_translate("MainWindow", "Delete row", None))
        self.btnLUpdateRow.setText(_translate("MainWindow", "Update row", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLists), _translate("MainWindow", "Lists", None))
        self.lblCorrectionsSelectMode.setText(_translate("MainWindow", "Mode", None))
        self.cboCCorrectionMode.setItemText(0, _translate("MainWindow", "RegEx", None))
        self.cboCCorrectionMode.setItemText(1, _translate("MainWindow", "Replace", None))
        self.cboCCorrectionMode.setItemText(2, _translate("MainWindow", "Word", None))
        self.lblCList.setText(_translate("MainWindow", "List", None))
        self.btnCInsertRow.setText(_translate("MainWindow", "Insert row", None))
        self.btnCDeleteRow.setText(_translate("MainWindow", "Delete row", None))
        self.btnCUpdateRow.setText(_translate("MainWindow", "Update row", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabCorrections), _translate("MainWindow", "Corrections", None))
        self.lblSFileEncoding.setText(_translate("MainWindow", "File encoding", None))
        self.chkSRemoveEmpty.setText(_translate("MainWindow", "Remove empty lines from EOF", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabSettings), _translate("MainWindow", "Settings", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionWiki.setText(_translate("MainWindow", "Wiki (online)", None))
        self.actionOpen_files.setText(_translate("MainWindow", "Open files...", None))
        self.actionAdd_new_dictionary_type.setText(_translate("MainWindow", "Add new dictionary type...", None))
        self.actionAdd_new_correction_type.setText(_translate("MainWindow", "Add new correction type...", None))
        self.actionOpenDatabase.setText(_translate("MainWindow", "Open database...", None))
        self.actionCreateDatabase.setText(_translate("MainWindow", "Create a new database...", None))
        self.actionAddNewCorrectionType.setText(_translate("MainWindow", "Add new correction type...", None))

