# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Nov 30 10:14:15 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setEnabled(True)
        self.tabMain.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabFix = QtGui.QWidget()
        self.tabFix.setObjectName(_fromUtf8("tabFix"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabFix)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lstFFileContents = QtGui.QListWidget(self.tabFix)
        self.lstFFileContents.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lstFFileContents.setObjectName(_fromUtf8("lstFFileContents"))
        self.gridLayout_3.addWidget(self.lstFFileContents, 4, 0, 2, 1)
        self.lblFFileContents = QtGui.QLabel(self.tabFix)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFFileContents.setFont(font)
        self.lblFFileContents.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblFFileContents.setObjectName(_fromUtf8("lblFFileContents"))
        self.gridLayout_3.addWidget(self.lblFFileContents, 3, 0, 1, 1)
        self.lstFLists = QtGui.QListWidget(self.tabFix)
        self.lstFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lstFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lstFLists.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lstFLists.setObjectName(_fromUtf8("lstFLists"))
        self.gridLayout_3.addWidget(self.lstFLists, 4, 1, 1, 1)
        self.lblFLists = QtGui.QLabel(self.tabFix)
        self.lblFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lblFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFLists.setFont(font)
        self.lblFLists.setObjectName(_fromUtf8("lblFLists"))
        self.gridLayout_3.addWidget(self.lblFLists, 3, 1, 1, 1)
        self.btnFStart = QtGui.QPushButton(self.tabFix)
        self.btnFStart.setEnabled(False)
        self.btnFStart.setMinimumSize(QtCore.QSize(175, 0))
        self.btnFStart.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btnFStart.setObjectName(_fromUtf8("btnFStart"))
        self.gridLayout_3.addWidget(self.btnFStart, 5, 1, 1, 1)
        self.txtFFile = QtGui.QLineEdit(self.tabFix)
        self.txtFFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.txtFFile.setReadOnly(True)
        self.txtFFile.setObjectName(_fromUtf8("txtFFile"))
        self.gridLayout_3.addWidget(self.txtFFile, 1, 0, 1, 1)
        self.lblFFile = QtGui.QLabel(self.tabFix)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFFile.setFont(font)
        self.lblFFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblFFile.setObjectName(_fromUtf8("lblFFile"))
        self.gridLayout_3.addWidget(self.lblFFile, 0, 0, 1, 1)
        self.btnFOpenFile = QtGui.QPushButton(self.tabFix)
        self.btnFOpenFile.setEnabled(False)
        self.btnFOpenFile.setMinimumSize(QtCore.QSize(175, 0))
        self.btnFOpenFile.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btnFOpenFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnFOpenFile.setObjectName(_fromUtf8("btnFOpenFile"))
        self.gridLayout_3.addWidget(self.btnFOpenFile, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 2)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.tabMain.addTab(self.tabFix, _fromUtf8(""))
        self.tabBatchFix = QtGui.QWidget()
        self.tabBatchFix.setObjectName(_fromUtf8("tabBatchFix"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabBatchFix)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblBFLists = QtGui.QLabel(self.tabBatchFix)
        self.lblBFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lblBFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBFLists.setFont(font)
        self.lblBFLists.setObjectName(_fromUtf8("lblBFLists"))
        self.gridLayout_2.addWidget(self.lblBFLists, 3, 1, 1, 1)
        self.btnBFOpenDir = QtGui.QPushButton(self.tabBatchFix)
        self.btnBFOpenDir.setEnabled(False)
        self.btnBFOpenDir.setMinimumSize(QtCore.QSize(175, 0))
        self.btnBFOpenDir.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btnBFOpenDir.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnBFOpenDir.setObjectName(_fromUtf8("btnBFOpenDir"))
        self.gridLayout_2.addWidget(self.btnBFOpenDir, 1, 1, 1, 1)
        self.lstBFFileList = QtGui.QListWidget(self.tabBatchFix)
        self.lstBFFileList.setObjectName(_fromUtf8("lstBFFileList"))
        self.gridLayout_2.addWidget(self.lstBFFileList, 4, 0, 2, 1)
        self.txtBFDir = QtGui.QLineEdit(self.tabBatchFix)
        self.txtBFDir.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.txtBFDir.setReadOnly(True)
        self.txtBFDir.setObjectName(_fromUtf8("txtBFDir"))
        self.gridLayout_2.addWidget(self.txtBFDir, 1, 0, 1, 1)
        self.lblBFFileList = QtGui.QLabel(self.tabBatchFix)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBFFileList.setFont(font)
        self.lblBFFileList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblBFFileList.setObjectName(_fromUtf8("lblBFFileList"))
        self.gridLayout_2.addWidget(self.lblBFFileList, 3, 0, 1, 1)
        self.lblBFPath = QtGui.QLabel(self.tabBatchFix)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblBFPath.setFont(font)
        self.lblBFPath.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblBFPath.setObjectName(_fromUtf8("lblBFPath"))
        self.gridLayout_2.addWidget(self.lblBFPath, 0, 0, 1, 1)
        self.btnBFStart = QtGui.QPushButton(self.tabBatchFix)
        self.btnBFStart.setEnabled(False)
        self.btnBFStart.setMinimumSize(QtCore.QSize(175, 0))
        self.btnBFStart.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btnBFStart.setObjectName(_fromUtf8("btnBFStart"))
        self.gridLayout_2.addWidget(self.btnBFStart, 5, 1, 1, 1)
        self.lstBFLists = QtGui.QListWidget(self.tabBatchFix)
        self.lstBFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lstBFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lstBFLists.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lstBFLists.setObjectName(_fromUtf8("lstBFLists"))
        self.gridLayout_2.addWidget(self.lstBFLists, 4, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 2)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.tabMain.addTab(self.tabBatchFix, _fromUtf8(""))
        self.tabLists = QtGui.QWidget()
        self.tabLists.setObjectName(_fromUtf8("tabLists"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabLists)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tblLLists = QtGui.QTableWidget(self.tabLists)
        self.tblLLists.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblLLists.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblLLists.setObjectName(_fromUtf8("tblLLists"))
        self.tblLLists.setColumnCount(0)
        self.tblLLists.setRowCount(0)
        self.tblLLists.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.tblLLists)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.btnLInsertRow = QtGui.QPushButton(self.tabLists)
        self.btnLInsertRow.setEnabled(False)
        self.btnLInsertRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLInsertRow.setObjectName(_fromUtf8("btnLInsertRow"))
        self.verticalLayout.addWidget(self.btnLInsertRow)
        self.btnLDeleteRow = QtGui.QPushButton(self.tabLists)
        self.btnLDeleteRow.setEnabled(False)
        self.btnLDeleteRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLDeleteRow.setObjectName(_fromUtf8("btnLDeleteRow"))
        self.verticalLayout.addWidget(self.btnLDeleteRow)
        self.btnLUpdateRow = QtGui.QPushButton(self.tabLists)
        self.btnLUpdateRow.setEnabled(False)
        self.btnLUpdateRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLUpdateRow.setObjectName(_fromUtf8("btnLUpdateRow"))
        self.verticalLayout.addWidget(self.btnLUpdateRow)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabMain.addTab(self.tabLists, _fromUtf8(""))
        self.tabCorrections = QtGui.QWidget()
        self.tabCorrections.setObjectName(_fromUtf8("tabCorrections"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tabCorrections)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tblCCorrections = QtGui.QTableWidget(self.tabCorrections)
        self.tblCCorrections.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblCCorrections.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblCCorrections.setObjectName(_fromUtf8("tblCCorrections"))
        self.tblCCorrections.setColumnCount(0)
        self.tblCCorrections.setRowCount(0)
        self.tblCCorrections.horizontalHeader().setVisible(False)
        self.tblCCorrections.verticalHeader().setVisible(False)
        self.horizontalLayout_3.addWidget(self.tblCCorrections)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblCorrectionsSelectMode = QtGui.QLabel(self.tabCorrections)
        self.lblCorrectionsSelectMode.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCorrectionsSelectMode.setFont(font)
        self.lblCorrectionsSelectMode.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblCorrectionsSelectMode.setObjectName(_fromUtf8("lblCorrectionsSelectMode"))
        self.verticalLayout_2.addWidget(self.lblCorrectionsSelectMode)
        self.cboCCorrectionMode = QtGui.QComboBox(self.tabCorrections)
        self.cboCCorrectionMode.setMinimumSize(QtCore.QSize(150, 0))
        self.cboCCorrectionMode.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboCCorrectionMode.setObjectName(_fromUtf8("cboCCorrectionMode"))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cboCCorrectionMode)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.lblCList = QtGui.QLabel(self.tabCorrections)
        self.lblCList.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCList.setFont(font)
        self.lblCList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblCList.setObjectName(_fromUtf8("lblCList"))
        self.verticalLayout_2.addWidget(self.lblCList)
        self.cboCList = QtGui.QComboBox(self.tabCorrections)
        self.cboCList.setMinimumSize(QtCore.QSize(150, 0))
        self.cboCList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboCList.setEditable(False)
        self.cboCList.setObjectName(_fromUtf8("cboCList"))
        self.verticalLayout_2.addWidget(self.cboCList)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.btnCInsertRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCInsertRow.setEnabled(False)
        self.btnCInsertRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCInsertRow.setObjectName(_fromUtf8("btnCInsertRow"))
        self.verticalLayout_2.addWidget(self.btnCInsertRow)
        self.btnCDeleteRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCDeleteRow.setEnabled(False)
        self.btnCDeleteRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCDeleteRow.setObjectName(_fromUtf8("btnCDeleteRow"))
        self.verticalLayout_2.addWidget(self.btnCDeleteRow)
        self.btnCUpdateRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCUpdateRow.setEnabled(False)
        self.btnCUpdateRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCUpdateRow.setObjectName(_fromUtf8("btnCUpdateRow"))
        self.verticalLayout_2.addWidget(self.btnCUpdateRow)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.tabMain.addTab(self.tabCorrections, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.lblSFileEncoding = QtGui.QLabel(self.tabSettings)
        self.lblSFileEncoding.setGeometry(QtCore.QRect(10, 10, 175, 16))
        self.lblSFileEncoding.setMinimumSize(QtCore.QSize(175, 0))
        self.lblSFileEncoding.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSFileEncoding.setFont(font)
        self.lblSFileEncoding.setObjectName(_fromUtf8("lblSFileEncoding"))
        self.cboSFileEncoding = QtGui.QComboBox(self.tabSettings)
        self.cboSFileEncoding.setGeometry(QtCore.QRect(10, 30, 175, 22))
        self.cboSFileEncoding.setMinimumSize(QtCore.QSize(175, 0))
        self.cboSFileEncoding.setMaximumSize(QtCore.QSize(175, 16777215))
        self.cboSFileEncoding.setObjectName(_fromUtf8("cboSFileEncoding"))
        self.chkSRemoveEmpty = QtGui.QCheckBox(self.tabSettings)
        self.chkSRemoveEmpty.setGeometry(QtCore.QRect(10, 70, 171, 16))
        self.chkSRemoveEmpty.setChecked(True)
        self.chkSRemoveEmpty.setObjectName(_fromUtf8("chkSRemoveEmpty"))
        self.tabMain.addTab(self.tabSettings, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_file = QtGui.QAction(MainWindow)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionWiki = QtGui.QAction(MainWindow)
        self.actionWiki.setObjectName(_fromUtf8("actionWiki"))
        self.actionOpen_files = QtGui.QAction(MainWindow)
        self.actionOpen_files.setObjectName(_fromUtf8("actionOpen_files"))
        self.actionAdd_new_dictionary_type = QtGui.QAction(MainWindow)
        self.actionAdd_new_dictionary_type.setObjectName(_fromUtf8("actionAdd_new_dictionary_type"))
        self.actionAdd_new_correction_type = QtGui.QAction(MainWindow)
        self.actionAdd_new_correction_type.setObjectName(_fromUtf8("actionAdd_new_correction_type"))
        self.actionOpenDatabase = QtGui.QAction(MainWindow)
        self.actionOpenDatabase.setObjectName(_fromUtf8("actionOpenDatabase"))
        self.actionCreateDatabase = QtGui.QAction(MainWindow)
        self.actionCreateDatabase.setObjectName(_fromUtf8("actionCreateDatabase"))
        self.actionAddNewCorrectionType = QtGui.QAction(MainWindow)
        self.actionAddNewCorrectionType.setObjectName(_fromUtf8("actionAddNewCorrectionType"))
        self.menuFile.addAction(self.actionCreateDatabase)
        self.menuFile.addAction(self.actionOpenDatabase)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionWiki)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "bwReplacer", None))
        self.lblFFileContents.setText(_translate("MainWindow", "File contents", None))
        self.lblFLists.setText(_translate("MainWindow", "Lists", None))
        self.btnFStart.setText(_translate("MainWindow", "Start", None))
        self.lblFFile.setText(_translate("MainWindow", "File", None))
        self.btnFOpenFile.setText(_translate("MainWindow", "Open file...", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabFix), _translate("MainWindow", "Fix", None))
        self.lblBFLists.setText(_translate("MainWindow", "Lists", None))
        self.btnBFOpenDir.setText(_translate("MainWindow", "Open directory...", None))
        self.lblBFFileList.setText(_translate("MainWindow", "File list", None))
        self.lblBFPath.setText(_translate("MainWindow", "Path", None))
        self.btnBFStart.setText(_translate("MainWindow", "Start", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabBatchFix), _translate("MainWindow", "Batch fix", None))
        self.btnLInsertRow.setText(_translate("MainWindow", "Insert row", None))
        self.btnLDeleteRow.setText(_translate("MainWindow", "Delete row", None))
        self.btnLUpdateRow.setText(_translate("MainWindow", "Update row", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLists), _translate("MainWindow", "Lists", None))
        self.lblCorrectionsSelectMode.setText(_translate("MainWindow", "Mode", None))
        self.cboCCorrectionMode.setItemText(0, _translate("MainWindow", "RegEx", None))
        self.cboCCorrectionMode.setItemText(1, _translate("MainWindow", "Replace", None))
        self.cboCCorrectionMode.setItemText(2, _translate("MainWindow", "Word", None))
        self.lblCList.setText(_translate("MainWindow", "List", None))
        self.btnCInsertRow.setText(_translate("MainWindow", "Insert row", None))
        self.btnCDeleteRow.setText(_translate("MainWindow", "Delete row", None))
        self.btnCUpdateRow.setText(_translate("MainWindow", "Update row", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabCorrections), _translate("MainWindow", "Corrections", None))
        self.lblSFileEncoding.setText(_translate("MainWindow", "File encoding", None))
        self.chkSRemoveEmpty.setText(_translate("MainWindow", "Remove empty lines from EOF", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabSettings), _translate("MainWindow", "Settings", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionWiki.setText(_translate("MainWindow", "Wiki (online)", None))
        self.actionOpen_files.setText(_translate("MainWindow", "Open files...", None))
        self.actionAdd_new_dictionary_type.setText(_translate("MainWindow", "Add new dictionary type...", None))
        self.actionAdd_new_correction_type.setText(_translate("MainWindow", "Add new correction type...", None))
        self.actionOpenDatabase.setText(_translate("MainWindow", "Open database...", None))
        self.actionCreateDatabase.setText(_translate("MainWindow", "Create a new database...", None))
        self.actionAddNewCorrectionType.setText(_translate("MainWindow", "Add new correction type...", None))

import icons_rc
