# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu May 29 11:30:24 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setEnabled(True)
        self.tabMain.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabFix = QtGui.QWidget()
        self.tabFix.setObjectName(_fromUtf8("tabFix"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabFix)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lstFLists = QtGui.QListWidget(self.tabFix)
        self.lstFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lstFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lstFLists.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.lstFLists.setObjectName(_fromUtf8("lstFLists"))
        self.gridLayout_2.addWidget(self.lstFLists, 1, 1, 1, 1)
        self.lblFLists = QtGui.QLabel(self.tabFix)
        self.lblFLists.setMinimumSize(QtCore.QSize(175, 0))
        self.lblFLists.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFLists.setFont(font)
        self.lblFLists.setObjectName(_fromUtf8("lblFLists"))
        self.gridLayout_2.addWidget(self.lblFLists, 0, 1, 1, 1)
        self.btnFStart = QtGui.QPushButton(self.tabFix)
        self.btnFStart.setEnabled(False)
        self.btnFStart.setMinimumSize(QtCore.QSize(175, 0))
        self.btnFStart.setMaximumSize(QtCore.QSize(175, 16777215))
        self.btnFStart.setObjectName(_fromUtf8("btnFStart"))
        self.gridLayout_2.addWidget(self.btnFStart, 2, 1, 1, 1)
        self.lblFFileList = QtGui.QLabel(self.tabFix)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFFileList.setFont(font)
        self.lblFFileList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblFFileList.setObjectName(_fromUtf8("lblFFileList"))
        self.gridLayout_2.addWidget(self.lblFFileList, 0, 0, 1, 1)
        self.tblFFileList = QtGui.QTableWidget(self.tabFix)
        self.tblFFileList.setAcceptDrops(True)
        self.tblFFileList.setDragEnabled(False)
        self.tblFFileList.setAlternatingRowColors(True)
        self.tblFFileList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblFFileList.setObjectName(_fromUtf8("tblFFileList"))
        self.tblFFileList.setColumnCount(0)
        self.tblFFileList.setRowCount(0)
        self.tblFFileList.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tblFFileList, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnFAddFiles = QtGui.QPushButton(self.tabFix)
        self.btnFAddFiles.setObjectName(_fromUtf8("btnFAddFiles"))
        self.horizontalLayout_6.addWidget(self.btnFAddFiles)
        self.btnFAddFolder = QtGui.QPushButton(self.tabFix)
        self.btnFAddFolder.setObjectName(_fromUtf8("btnFAddFolder"))
        self.horizontalLayout_6.addWidget(self.btnFAddFolder)
        self.btnFRemoveFiles = QtGui.QPushButton(self.tabFix)
        self.btnFRemoveFiles.setEnabled(False)
        self.btnFRemoveFiles.setObjectName(_fromUtf8("btnFRemoveFiles"))
        self.horizontalLayout_6.addWidget(self.btnFRemoveFiles)
        self.btnFClearList = QtGui.QPushButton(self.tabFix)
        self.btnFClearList.setEnabled(False)
        self.btnFClearList.setObjectName(_fromUtf8("btnFClearList"))
        self.horizontalLayout_6.addWidget(self.btnFClearList)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.tabMain.addTab(self.tabFix, _fromUtf8(""))
        self.tabLists = QtGui.QWidget()
        self.tabLists.setObjectName(_fromUtf8("tabLists"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabLists)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnLDeleteRow = QtGui.QPushButton(self.tabLists)
        self.btnLDeleteRow.setEnabled(False)
        self.btnLDeleteRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLDeleteRow.setObjectName(_fromUtf8("btnLDeleteRow"))
        self.gridLayout.addWidget(self.btnLDeleteRow, 1, 1, 1, 1)
        self.btnLUpdateRow = QtGui.QPushButton(self.tabLists)
        self.btnLUpdateRow.setEnabled(False)
        self.btnLUpdateRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLUpdateRow.setObjectName(_fromUtf8("btnLUpdateRow"))
        self.gridLayout.addWidget(self.btnLUpdateRow, 1, 2, 1, 1)
        self.btnLInsertRow = QtGui.QPushButton(self.tabLists)
        self.btnLInsertRow.setEnabled(False)
        self.btnLInsertRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLInsertRow.setObjectName(_fromUtf8("btnLInsertRow"))
        self.gridLayout.addWidget(self.btnLInsertRow, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.tblLLists = QtGui.QTableWidget(self.tabLists)
        self.tblLLists.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblLLists.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblLLists.setObjectName(_fromUtf8("tblLLists"))
        self.tblLLists.setColumnCount(0)
        self.tblLLists.setRowCount(0)
        self.tblLLists.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tblLLists, 0, 0, 1, 4)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabMain.addTab(self.tabLists, _fromUtf8(""))
        self.tabCorrections = QtGui.QWidget()
        self.tabCorrections.setObjectName(_fromUtf8("tabCorrections"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabCorrections)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnCInsertRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCInsertRow.setEnabled(False)
        self.btnCInsertRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCInsertRow.setObjectName(_fromUtf8("btnCInsertRow"))
        self.gridLayout_5.addWidget(self.btnCInsertRow, 3, 0, 1, 1)
        self.lblCList = QtGui.QLabel(self.tabCorrections)
        self.lblCList.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCList.setFont(font)
        self.lblCList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblCList.setObjectName(_fromUtf8("lblCList"))
        self.gridLayout_5.addWidget(self.lblCList, 0, 1, 1, 1)
        self.cboCList = QtGui.QComboBox(self.tabCorrections)
        self.cboCList.setMinimumSize(QtCore.QSize(150, 0))
        self.cboCList.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboCList.setEditable(False)
        self.cboCList.setObjectName(_fromUtf8("cboCList"))
        self.gridLayout_5.addWidget(self.cboCList, 1, 1, 1, 1)
        self.lblCorrectionsSelectMode = QtGui.QLabel(self.tabCorrections)
        self.lblCorrectionsSelectMode.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCorrectionsSelectMode.setFont(font)
        self.lblCorrectionsSelectMode.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lblCorrectionsSelectMode.setObjectName(_fromUtf8("lblCorrectionsSelectMode"))
        self.gridLayout_5.addWidget(self.lblCorrectionsSelectMode, 0, 0, 1, 1)
        self.cboCCorrectionMode = QtGui.QComboBox(self.tabCorrections)
        self.cboCCorrectionMode.setMinimumSize(QtCore.QSize(150, 0))
        self.cboCCorrectionMode.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboCCorrectionMode.setObjectName(_fromUtf8("cboCCorrectionMode"))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.cboCCorrectionMode.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.cboCCorrectionMode, 1, 0, 1, 1)
        self.btnCUpdateRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCUpdateRow.setEnabled(False)
        self.btnCUpdateRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCUpdateRow.setObjectName(_fromUtf8("btnCUpdateRow"))
        self.gridLayout_5.addWidget(self.btnCUpdateRow, 3, 2, 1, 1)
        self.btnCDeleteRow = QtGui.QPushButton(self.tabCorrections)
        self.btnCDeleteRow.setEnabled(False)
        self.btnCDeleteRow.setMinimumSize(QtCore.QSize(150, 0))
        self.btnCDeleteRow.setObjectName(_fromUtf8("btnCDeleteRow"))
        self.gridLayout_5.addWidget(self.btnCDeleteRow, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 3, 3, 1, 1)
        self.tblCCorrections = QtGui.QTableWidget(self.tabCorrections)
        self.tblCCorrections.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblCCorrections.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblCCorrections.setObjectName(_fromUtf8("tblCCorrections"))
        self.tblCCorrections.setColumnCount(0)
        self.tblCCorrections.setRowCount(0)
        self.tblCCorrections.horizontalHeader().setVisible(False)
        self.tblCCorrections.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tblCCorrections, 2, 0, 1, 4)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 2, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabMain.addTab(self.tabCorrections, _fromUtf8(""))
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.gridLayoutWidget = QtGui.QWidget(self.tabLog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 491))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.btnLClearLog = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnLClearLog.setMinimumSize(QtCore.QSize(150, 0))
        self.btnLClearLog.setObjectName(_fromUtf8("btnLClearLog"))
        self.gridLayout_6.addWidget(self.btnLClearLog, 1, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.chkLLogFixes = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkLLogFixes.setChecked(True)
        self.chkLLogFixes.setObjectName(_fromUtf8("chkLLogFixes"))
        self.gridLayout_6.addWidget(self.chkLLogFixes, 1, 0, 1, 1)
        self.lstLLog = QtGui.QListWidget(self.gridLayoutWidget)
        self.lstLLog.setObjectName(_fromUtf8("lstLLog"))
        self.gridLayout_6.addWidget(self.lstLLog, 0, 0, 1, 3)
        self.tabMain.addTab(self.tabLog, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.lblSFileEncoding = QtGui.QLabel(self.tabSettings)
        self.lblSFileEncoding.setGeometry(QtCore.QRect(10, 10, 175, 16))
        self.lblSFileEncoding.setMinimumSize(QtCore.QSize(175, 0))
        self.lblSFileEncoding.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSFileEncoding.setFont(font)
        self.lblSFileEncoding.setObjectName(_fromUtf8("lblSFileEncoding"))
        self.cboSFileEncoding = QtGui.QComboBox(self.tabSettings)
        self.cboSFileEncoding.setGeometry(QtCore.QRect(10, 30, 175, 22))
        self.cboSFileEncoding.setMinimumSize(QtCore.QSize(175, 0))
        self.cboSFileEncoding.setMaximumSize(QtCore.QSize(175, 16777215))
        self.cboSFileEncoding.setObjectName(_fromUtf8("cboSFileEncoding"))
        self.chkSRemoveEmpty = QtGui.QCheckBox(self.tabSettings)
        self.chkSRemoveEmpty.setGeometry(QtCore.QRect(10, 70, 381, 16))
        self.chkSRemoveEmpty.setChecked(True)
        self.chkSRemoveEmpty.setObjectName(_fromUtf8("chkSRemoveEmpty"))
        self.tabMain.addTab(self.tabSettings, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuFix = QtGui.QMenu(self.menubar)
        self.menuFix.setObjectName(_fromUtf8("menuFix"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionWiki = QtGui.QAction(MainWindow)
        self.actionWiki.setObjectName(_fromUtf8("actionWiki"))
        self.actionOpenDatabase = QtGui.QAction(MainWindow)
        self.actionOpenDatabase.setObjectName(_fromUtf8("actionOpenDatabase"))
        self.actionNewDatabase = QtGui.QAction(MainWindow)
        self.actionNewDatabase.setObjectName(_fromUtf8("actionNewDatabase"))
        self.actionAddFiles = QtGui.QAction(MainWindow)
        self.actionAddFiles.setObjectName(_fromUtf8("actionAddFiles"))
        self.actionAddFolder = QtGui.QAction(MainWindow)
        self.actionAddFolder.setObjectName(_fromUtf8("actionAddFolder"))
        self.actionRemoveFiles = QtGui.QAction(MainWindow)
        self.actionRemoveFiles.setEnabled(False)
        self.actionRemoveFiles.setObjectName(_fromUtf8("actionRemoveFiles"))
        self.actionClearList = QtGui.QAction(MainWindow)
        self.actionClearList.setEnabled(False)
        self.actionClearList.setObjectName(_fromUtf8("actionClearList"))
        self.actionStart = QtGui.QAction(MainWindow)
        self.actionStart.setEnabled(False)
        self.actionStart.setObjectName(_fromUtf8("actionStart"))
        self.menuFile.addAction(self.actionNewDatabase)
        self.menuFile.addAction(self.actionOpenDatabase)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionWiki)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFix.addAction(self.actionAddFiles)
        self.menuFix.addAction(self.actionAddFolder)
        self.menuFix.addAction(self.actionRemoveFiles)
        self.menuFix.addAction(self.actionClearList)
        self.menuFix.addSeparator()
        self.menuFix.addAction(self.actionStart)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFix.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabMain, self.tblFFileList)
        MainWindow.setTabOrder(self.tblFFileList, self.lstFLists)
        MainWindow.setTabOrder(self.lstFLists, self.btnFAddFiles)
        MainWindow.setTabOrder(self.btnFAddFiles, self.btnFAddFolder)
        MainWindow.setTabOrder(self.btnFAddFolder, self.btnFRemoveFiles)
        MainWindow.setTabOrder(self.btnFRemoveFiles, self.btnFClearList)
        MainWindow.setTabOrder(self.btnFClearList, self.btnFStart)
        MainWindow.setTabOrder(self.btnFStart, self.tblLLists)
        MainWindow.setTabOrder(self.tblLLists, self.btnLInsertRow)
        MainWindow.setTabOrder(self.btnLInsertRow, self.btnLDeleteRow)
        MainWindow.setTabOrder(self.btnLDeleteRow, self.btnLUpdateRow)
        MainWindow.setTabOrder(self.btnLUpdateRow, self.cboCCorrectionMode)
        MainWindow.setTabOrder(self.cboCCorrectionMode, self.cboCList)
        MainWindow.setTabOrder(self.cboCList, self.tblCCorrections)
        MainWindow.setTabOrder(self.tblCCorrections, self.btnCInsertRow)
        MainWindow.setTabOrder(self.btnCInsertRow, self.btnCDeleteRow)
        MainWindow.setTabOrder(self.btnCDeleteRow, self.btnCUpdateRow)
        MainWindow.setTabOrder(self.btnCUpdateRow, self.cboSFileEncoding)
        MainWindow.setTabOrder(self.cboSFileEncoding, self.chkSRemoveEmpty)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "bwReplacer", None))
        self.lblFLists.setText(_translate("MainWindow", "Lists", None))
        self.btnFStart.setText(_translate("MainWindow", "Start", None))
        self.lblFFileList.setText(_translate("MainWindow", "File list", None))
        self.btnFAddFiles.setText(_translate("MainWindow", "Add files", None))
        self.btnFAddFolder.setText(_translate("MainWindow", "Add folder", None))
        self.btnFRemoveFiles.setText(_translate("MainWindow", "Remove files", None))
        self.btnFClearList.setText(_translate("MainWindow", "Clear list", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabFix), _translate("MainWindow", "Fix", None))
        self.btnLDeleteRow.setText(_translate("MainWindow", "Delete row", None))
        self.btnLUpdateRow.setText(_translate("MainWindow", "Update row", None))
        self.btnLInsertRow.setText(_translate("MainWindow", "Insert row", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLists), _translate("MainWindow", "Lists", None))
        self.btnCInsertRow.setText(_translate("MainWindow", "Insert row", None))
        self.lblCList.setText(_translate("MainWindow", "List", None))
        self.lblCorrectionsSelectMode.setText(_translate("MainWindow", "Mode", None))
        self.cboCCorrectionMode.setItemText(0, _translate("MainWindow", "RegEx", None))
        self.cboCCorrectionMode.setItemText(1, _translate("MainWindow", "Replace", None))
        self.cboCCorrectionMode.setItemText(2, _translate("MainWindow", "Word", None))
        self.btnCUpdateRow.setText(_translate("MainWindow", "Update row", None))
        self.btnCDeleteRow.setText(_translate("MainWindow", "Delete row", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabCorrections), _translate("MainWindow", "Corrections", None))
        self.btnLClearLog.setText(_translate("MainWindow", "Clear log", None))
        self.chkLLogFixes.setText(_translate("MainWindow", "Log fixes", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLog), _translate("MainWindow", "Log", None))
        self.lblSFileEncoding.setText(_translate("MainWindow", "File encoding", None))
        self.chkSRemoveEmpty.setText(_translate("MainWindow", "Remove empty lines from EOF", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabSettings), _translate("MainWindow", "Settings", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuFix.setTitle(_translate("MainWindow", "Fix", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionWiki.setText(_translate("MainWindow", "Wiki (online)", None))
        self.actionOpenDatabase.setText(_translate("MainWindow", "Open database", None))
        self.actionNewDatabase.setText(_translate("MainWindow", "New database", None))
        self.actionNewDatabase.setToolTip(_translate("MainWindow", "New database", None))
        self.actionAddFiles.setText(_translate("MainWindow", "Add files", None))
        self.actionAddFiles.setToolTip(_translate("MainWindow", "Add files", None))
        self.actionAddFolder.setText(_translate("MainWindow", "Add folder", None))
        self.actionAddFolder.setToolTip(_translate("MainWindow", "Add folder", None))
        self.actionRemoveFiles.setText(_translate("MainWindow", "Remove files", None))
        self.actionRemoveFiles.setToolTip(_translate("MainWindow", "Remove files", None))
        self.actionClearList.setText(_translate("MainWindow", "Clear list", None))
        self.actionClearList.setToolTip(_translate("MainWindow", "Clear list", None))
        self.actionStart.setText(_translate("MainWindow", "Start", None))
        self.actionStart.setToolTip(_translate("MainWindow", "Start", None))

